= Discussions in Canvas at Olympic College
Amelia Garripoli <agarripoli@olympic.edu>
v2016 September 14 CC-BY-SA-4.0

This talk is available at http://tinyurl.com/ocdiscuss[tinyurl.com/ocdiscuss]

:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
:encoding: utf-8
:lang: en
:toc: left
:toclevels: 2
:numbered:
:sectlinks:
:sectanchors:
:copyright: CC-BY-SA-4.0



////
Generate PDF from directory with book.adoc in it with the command
asciidoctor-pdf -a toc book.adoc
prepare to be amazed 

Generate HTML: (working on actual slides,...)
asciidoctor book.adoc
////

:numbered!:
== Canvas Discussions

Sure there are the nuts and bolts, but how do you make them useful for students?

== Discussions

* <<echos>>
* <<pick-a-term>>
* Pick-a-topic
* Ask One, Answer One
* Future Application
* Best Practices 
* Troubleshooting
* Random choice
* Series of questions
* Research
* Find a Video
* Peer Review of a Lab

== Echos

* Asking a question that has them look into a module
topic in more depth
** does this work for you?
** lots of echos of the book or the video/class
** not much outside effort

* Posts tend to be repetitive
* Responses tend to be repetitive and fluffy
* Word counts lead to "fluff generators" (not a course outcome)

== Pick-a-term 

* Have students sign up for a word from your module vocabulary list

* They post a definition, an example, a source
* They post responses "expanding on the post" -- this is difficult for many. Good idea to post a response in the first board to give them an example

* good variety
* may have to step in and adjust incorrect posts

== Pick-a-topic (think wiki)

* Have students sign up for a topic
  ** you coordinate (do you have time?)
  ** students self-sign-up (Student edited Page)
* Responses can:
  ** expand the post
  ** give constructive criticism

* Can expose the posts from the start
* Posts are refreshing
* Can get some echos in responses (remember, they see them all)  
* Can potentially give credit for updating or adding to their initial post

== Ask One, Answer One

* Have students ask an open-ended question about the module
  ** for example, "there's a bug in this code, what can you do to figure out where it is"
  
* Each student has to answer one (should answer one without an answer; may be hard to manage...)

* This is a form of self-review, but can be unbalanced if skill levels are wide
* You can seed it with a few open-ended questions to set an example, and to help the early responders get their work done

* You can give bonuses for additional questions (posted after the due date! so someone doesn't take up the potential question space)

== Future Application

* Ask students to describe how they will use this module's skills in the future

* Can be difficult for those who are present but not goal oriented
* Tends to spark some interesting responses, as people see things in others' future use they hadn't thought about
* Need to make sure the class discussion/supporting material includes "in the workplace" type of information for students to tie this to their potential future


== Best Practices

* Ask students to provide a "best practice" based on the course material
* Material has to be convention-driven for this to work, not prescribed; it has to have "wiggle room" for it to need best practices.
* Tends to spark some interesting responses, as people see things in others' best practices they hadn't thought about 
* Reinforces the value of the conventions
* May need to step in if the b.p. contains errors in thinking


== Troubleshooting

* Ask students to provide trouble-shooting advice based on the course material
* Since everything can be done wrong, this is useful in helping them guide one another
* Need to be careful that they don't share homework solutions in this
* Tends to spark some interesting responses, as people see things in others' troubleshooting they hadn't considered 
* May need to step in if the advice contains errors in thinking


== Random choice

* Provide 4-5 questions and let students pick the one they want to respond to.
* Surprisingly, not everyone will choose the first one.
* Some repetition, but gives students posts to respond to that are not on their own topic
* Students can self-select to respond to someone who did the same question, or who did a different one
* Students sometimes respond to all briefly in the hopes of getting full credit (but such posts are very light on content)


== Series of questions

* Provide a series of related questions or points for them to respond to
** Example:
*** When was the first time you used a computer?
*** What has changed about computers since you first used one?
*** What do you view as the most interesting change in computers since you first knew about them?
* Makes it easier to have a post with enough concrete content
* Remind people to use examples from their own experience (helps limit plagiarizability)
* Responses can often be challenging; a student's response to someone else tends to be an echo of their own post
  

== Research

* Give (or have self-signup) a research topic: material not covered in the course, but relevant to it
* The post is a summary of findings with sources cited
* Responders have trouble with this: tend to say "good job". Good to direct them with something like "describe how you might make use of the poster's information in your future work in this area"


== Find a Video

* Have them look for a video, tutorial, or other relevant course supporting material, describe it and evaluate it for course use and after course use
* Responders compare your find to theirs (or to another one if they found the same one)
* Lets a student respond to themselves and get it done

  
== Peer Review of a Lab

* Have students post their lab work
* The key work here is the response; have them evaluate their peers' work, providing positive feedback _and_ constructive criticism.
* Lets students practice higher-level skills of evaluation on their peers' work
* Need to have labs be tailored so plagiarism isn't directly possible (best with personal projects)
* Lets everyone see everyones' work, unlike a Canvas "peer review" -- they can comment on the reviews, and learn from how their peers do the reviews.

== Other possibilities 

many from 
http://www.levy.k12.fl.us/instruction/Instructional_Tools/60formativeassessment.pdf[60 Formative Assessments by K Lambert]

* Present students with common or predictable misconceptions about a designated concept,
principle, or process. Ask them whether they agree or disagree and explain why.
* Give them a series of prompts to complete to reflect on the module's contents, such as:
** I became more aware of ...
** I was surprised about ...
** I related to ...
* Each student is given a letter, and must write on a word relevant to the module that starts with that letter
* Provide an example of your own devising that exhibits an outcome of the module (Blooms 2 outcomes are great for this)
* Write a 3-2-1 post: 
** 3 things you found out
** 2 interesting things
** 1 question you still have
** responses can critique, answer, expand on the posts
* Provide 3-5 statements that aren’t clearly true or false, but are somewhat debatable. Have them evaluate them on a Likert scale (strongly agree to strongly disagree) and explain their evaluation
* Circle: something still going around in your head. Triangle: something pointed that stood out in your mind. Square: Something that "squared" or agreed with your thinking.
* KWL: In your post write what you already knew before the module, what you want to learn but don't know, and what you learned in this module. (can lead to vague posts)



== Questions?


This talk is available at http://tinyurl.com/ocdiscuss[tinyurl.com/ocdiscuss]
